theme: jekyll-theme-minimal
title: Spoken Arabic
description: Videos, audio files, texts and scripts used to produce and analyse a small corpus of spoken Arabic in the dialect of Oman
repository: sixtyfive/spoken-arabic
